int controller_loadFromText(char* path, LinkedList* pArrayListVentas);
//int controller_loadFromBinary(char* path , LinkedList* pArrayListEmployee);
//int controller_addEmployee(LinkedList* pArrayListEmployee);
//int controller_editEmployee(LinkedList* pArrayListEmployee);
//int controller_removeEmployee(LinkedList* pArrayListEmployee);
int controller_ListVentas(LinkedList* pArrayListVentas);
//int controller_sortEmployee(LinkedList* pArrayListEmployee);
int controller_saveAsTextVentas(char* path, LinkedList* pArrayListVentas);
//int controller_saveAsBinary(char* path , LinkedList* pArrayListEmployee);
int idMaxArray(LinkedList* pArrayVentas);
int cantidadFotos(LinkedList* pArrayList);
int montoMayor150(void* p);
int montoMayor300(void* p);
int PolaroidReveladas(void* p);
